# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10rcAy7RlePidTx23KSSlZcGQFf9VN8By
"""

#importamos las librerias de pyspark
import csv
from pyspark.sql import SparkSession
from pyspark.sql.functions import *


#creamos el spark como registro de asaitencia_media
spark= SparkSession.builder.appName("Registro de asistencia_media").getOrCreate()
# llamamos el archivo estados
csv_file = "Estados.csv"
# que lea el archivo
Datos_t = spark.read.csv(csv_file, header=True, inferSchema=True)

Datos_t.show()#y este muestre los datos


#con esta consulta, vamos a ver la correlacion de las asistencias o estados que tiene las personas
data_var=[(3,4),(4,3),(5,2),(4,1),(3,2),(4,3), (1,2), (2,3), (5,2), (4,1), (3,1), (2,2), (2, 3), (2,4), (1,4)]
columns_var = ["asistencia ", "tardanzas"]
variable_corr = spark.createDataFrame(data_var, columns_var)

correlacion = variable_corr.select(corr(col("asistencia"), col("tardanzas")).alias("correlacion")).collect()[0]["correlacion"]

variable_corr = spark.createDataFrame(data_var, columns_var)
print("La correlacion es:", correlacion)